version: '3.8'

services:
  web:
    build: ./services/web
    command: python3 manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/application/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=application_db
      - POSTGRES_PASSWORD=application_db
      - POSTGRES_DB=application_db_dev

volumes:
  postgres_data:
